concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    uses: praw-dev/.github/.github/workflows/ci.yml@e86d5e7389cc00472a01675465bfa72b1dffd884 # v1.2.0
    with:
      min_python: "3.10"
      python_versions: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
name: CI
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
permissions: read-all
