concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    uses: praw-dev/.github/.github/workflows/ci.yml@ec3a733628adc5bd596def5294dae9fb4eb1e501 # v1.6.0
    with:
      min_python: "3.10"
      python_versions: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
name: CI
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
permissions:
  contents: read
