concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    uses: praw-dev/.github/.github/workflows/ci.yml@1149a76ab5ae488cdc632ce70548ec3c1a278305 # v1.3.0
    with:
      min_python: "3.10"
      python_versions: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
name: CI
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
permissions: read-all
