jobs:
  prepare_release:
    name: Prepare Release
    secrets: inherit
    uses: praw-dev/.github/.github/workflows/prepare_release.yml@main
    with:
      package: prawcore
      version: ${{ inputs.version }}
      version_file: __init__.py
name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to prepare for release
        required: true
permissions:
  contents: read
  pull-requests: write
