jobs:
  tag_release:
    name: Tag Release
    secrets: inherit
    uses: praw-dev/.github/.github/workflows/tag_release.yml@d982d39c7343205d239f7b8929592f538fb01662 # main 2026-06-06
name: Tag Release
on:
  push:
    branches: [ main, release_test ]
permissions:
  contents: write
